#ifndef KRX_KOBJC_OBJFW_DEFS_H
#define KRX_KOBJC_OBJFW_DEFS_H

#define OF_OBJFW_RUNTIME
#define OF_HAVE_ATOMIC_OPS
#define OF_HAVE_ATOMIC_BUILTINS
#define HAVE_DWARF_EXCEPTIONS

#endif /* KRX_KOBJC_OBJFW_DEFS_H */
