SUB=..
PKGNAME=bash
DISTFILES="https://ftp.gnu.org/gnu/bash/bash-5.2.15.tar.gz"

CONFSUBS="bash-5.2.15/support/config.sub"
CONFIGURE_SCRIPT="bash-5.2.15/configure"
CONFIGURE_ARGS+="--without-bash-malloc"

.include "../buildsup/krx.gnu.mk"