.Dd October 5, 2024
.Dt INTRO 9
.Os
.Sh NAME
.Nm intro
.Nd Introduction to Keyronex kernel internals
.Sh DESCRIPTION
This section contains documentation related to the internals of the kernel.
It covers kernel facilities and functions that are relevant to developers of the
kernel, drivers, and modules.
.Pp
These manual pages are intended to be the primary reference for kernel
programming and a practical complement to in-source documentation, which focuses
on theoretical and design aspects.
.Pp
Below are presented sections for each high-level division of the kernel,
containing links to individual subsystems and functions.
.Sh KERNEL
.Bl -tag -width Ds
.It Xr ipl 9
Interrupt Priority Level mechanism.
.It Xr dpc 9
Deferred Procedure Call mechanism.
.It Xr locking 9
Introduction to locking and synchronisation mechanisms.
.It Xr spinlock 9
Spin lock mutual exclusion mechanism.
.It Xr rcu 9
Read-Copy-Update work deferral mechanism.
.Sh HISTORY
The Keyronex kernel manual pages were begun on October the 5th, 2024.
