name: Weekly Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-amd64:
    name: amd64-build
    uses: ./.github/workflows/weekly-common.yaml
    with:
      arch: amd64

  build-m68k:
    name: build-m68k
    uses: ./.github/workflows/weekly-common.yaml
    with:
      arch: m68k

  build-riscv:
    name: build-riscv
    uses: ./.github/workflows/weekly-common.yaml
    with:
      arch: riscv64

  build-aarch64:
    name: build-aarch64
    uses: ./.github/workflows/weekly-common.yaml
    with:
      arch: aarch64
