name: Weekly Keyronex build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clone submodules
        run: git submodule update --init

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autopoint \
            gettext \
            git \
            gperf \
            help2man \
            libgmp-dev \
            libmpc-dev \
            libmpfr-dev \
            libtool \
            m4 \
            meson \
            pkg-config \
            python3 \
            python3-mako \
            python3-pip \
            texinfo \
            yacc \
            xorriso
          sudo pip install xbstrap

      - name: Build everything
        run: make all ARCH=amd64
  build-m68k:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clone submodules
        run: git submodule update --init

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autopoint \
            gettext \
            git \
            gperf \
            help2man \
            libgmp-dev \
            libmpc-dev \
            libmpfr-dev \
            libtool \
            m4 \
            meson \
            pkg-config \
            python3 \
            python3-mako \
            python3-pip \
            texinfo \
            yacc \
            xorriso
          sudo pip install xbstrap

      - name: Build everything
        run: make all ARCH=m68k
