name: Weekly Keyronex build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clone submodules
        run: git submodule update --init

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autopoint \
            gettext \
            git \
            gperf \
            help2man \
            libgmp-dev \
            libmpc-dev \
            libmpfr-dev \
            libtool \
            m4 \
            meson \
            pkg-config \
            python3 \
            python3-mako \
            python3-pip \
            texinfo \
            yacc \
            xorriso
          sudo pip install xbstrap

      - name: Build everything
        run: make all

      - name: Set TAG_DATE environment variable
        run: echo "TAG_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Build and rename ISO
        run: |
          make iso
          mv build/barebones.iso keyronex-$TAG_DATE.iso

      - name: Create a tarball of the system root
        run: tar -C build/system-root/ -cf keyronex-sysroot-$TAG_DATE.tar.zst --zstd .

      - name: Tag and push new release tag
        run: |
          git tag weekly-$TAG_DATE
          git push --tags

      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          name: Weekly build ${{ env.TAG_DATE }}
          tag_name: weekly-${{ env.TAG_DATE }}
          body: Image of a weekly Keyronex build together with a system root tarball.
          files: |
            keyronex-${{ env.TAG_DATE }}.iso
            keyronex-sysroot-${{ env.TAG_DATE }}.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
